### ISSUE TITLE
Outdated documentation reference in example.env

### ISSUE THREAD

**Issue by OskarD** [twilio/twilio-voice-react-native-app#143]
The ancor on this link does not exist anymore

https://github.com/twilio/twilio-voice-react-native-app/blob/1a3fb6a0c9a498cd4e7e895a271f4e63004e33a8/server/example.env#L25C1-L25C80

**Comment by mhuynh5757** [comment]
Hi @OskarD, thanks for bringing this our attention. We will fix this as soon as we can!
