### ISSUE TITLE
Step by step tutorial for integrating into a RN app

### ISSUE THREAD

**Issue by ilyagru** [twilio/twilio-voice-react-native-app#149]
Hi!

Thank you for this example, but is there any documentation or step by step tutorial for integrating Twillio Voice into a new RN app from scratch? What permissions should be added, etc.? This repo is quite an overkill and it's not clear what is minimally needed to integrate Twillio, since not all projects use Redux and Auth0.

**Comment by mhuynh5757** [comment]
Hi @ilyagru I understand your concern, thanks for helping us to understand what provides the best value for our customers. I see your comment in the other GitHub issue here: https://github.com/twilio/twilio-voice-react-native/issues/295

I'll surface this with my team and see what we can do to help.
