### ISSUE TITLE
unable to integrate in expo

### ISSUE THREAD

**Issue by raghavendra-10** [twilio/twilio-voice-react-native-app#151]
![image_2024-08-26_125511175](https://github.com/user-attachments/assets/57ff19e5-61d2-472e-abca-eea55382128b)

in the above image you can see iam passing the access token but iam facing those errors , can anyone walk me through .

**Comment by mhuynh5757** [comment]
Hi @raghavendra-10 thanks for reaching out. We currently don't support Expo with the Twilio Voice React Native Voice SDK, but it's on our radar and the team is discussing priorities surrounding it. I can't promise any timelines at this point, but please stay tuned! Thanks for your patience.
