### ISSUE TITLE
Android / Getting GET_ACCESS_TOKEN_REJECTED

### ISSUE THREAD

**Issue by spuri22** [twilio/twilio-voice-react-native-app#85]
I am trying to bring up the android app based on the instructions.
Login succeeds, but I get GET_ACCESS_TOKEN_REJECTED. 
What could be the cause? Any configuration I am missing?

Logs on Android emulator console.

 LOG  registration/loginAndRegister/pending
 LOG  user/login/pending
 LOG  user/login/fulfilled
 LOG  voice/getAccessToken/pending
 LOG  voice/getAccessToken/rejected {
  "reason": "FETCH_ERROR",
  "error": {
    "name": "TypeError",
    "message": "Network request failed",
    "stack": "TypeError: Network request failed\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:21299:33)\n    at apply (native)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:26307:26)\n    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:26246:17)\n    at callTimers (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:26402:19)\n    at apply (native)\n    at __callFunction (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:2435:36)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:2197:31)\n    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:2387:15)\n    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.twiliovoicereactnativereferenceapp&modulesOnly=false&runModule=true:2196:21)"
  }
}
 LOG  registration/loginAndRegister/rejected {
  "reason": "GET_ACCESS_TOKEN_REJECTED"
}
 ERROR  {"reason": "GET_ACCESS_TOKEN_REJECTED"}

**Comment by mhuynh5757** [comment]
Closing this issue now, please reach out again if you need further assistance.
